version: '3.8'

services:
  app:
    image: fabrizio9898/backendproyect
    ports:
      - '3001:3000'
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb: 
    image: postgres
    env_file:
      - .env.development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
